# Lab 2 - Rectangular data and Pandas

## Purpose
Give an introduction to  
* Jupyter Notebook
* Rectangular data
* Variables and records
* Independent and dependent variables
* Pandas and Numpy Libraries
* Exploratory Data Analysis

## Methodology
We will be using the Pandas library to load a dataset, perform operation and conduct some data analysis. Some challenges are presented at the end.

## Results
Some knowledge on how to load, write and manipulate rectangular data in Python. First hands on real data.

## Suggested next steps
Explore different types of data visualizations. Check [Python Graph Gallery](https://www.python-graph-gallery.com/) for ideas. This will be the topic of next week.


# Jupyter Notebooks

Anaconda will be our preference as a Python environment manager. If you haven't done it already, [install](https://www.anaconda.com/) it and follow the `intructions.md` file of the first week (available in moodle).

Jupyter Lab/Notebooks will be our IDE of preference.

Jupyter Notebooks are composed by Cells.

Cells can be either Markdown or Code.  

- Markdown cells allows us to write text, formulae, add images and explain things in the same way we would do in a normal notebook. Here is a [cheat sheet](https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf) for Markdown Sintax.

- Code Cells allows us to execute code.

Here is a Jupyter Notebook commands [cheat sheet](https://www.edureka.co/blog/wp-content/uploads/2018/10/Jupyter_Notebook_CheatSheet_Edureka.pdf) although you can also use the Help tab.

Useful Jupyter Notebook shortcuts:
- Esc and Enter to toggle between edit mode (notice how the colour of the cell on the left changes)
- A - new cell after current cell
- B - new cell before current cell
- Shit + Enter - execute cell and go to the next
- Ctrl + Enter - execute cell and remain on current
- DD - delete cell
- Z  - undo deleted

In [56]:
# install necessary packages
!pip install pandas
!pip instal numpy

Defaulting to user installation because normal site-packages is not writeable
ERROR: unknown command "instal" - maybe you meant "install"


## Numpy

In [57]:
import numpy as np

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. Also, it offers comprehensive mathematical functions, random number generators, linear algebra routines, Fourier transforms, and more.

## Before moving forward

Explore Numpy `dot` function

In [58]:
v1 = [1,2,3,4]
v2 = [3,2,5,4]

# "np" is the alias for numpy library when imported like 'import numpy as np'
# print the dot product of v1 and v2 using numpy
np.dot(v1, v2)

np.int64(38)

You can check [`numpy documentation`](https://numpy.org/doc/stable/reference/generated/numpy.dot.html) or use the `help` function to understand more about any function

In [59]:
help(np.dot)

Help on _ArrayFunctionDispatcher in module numpy:

dot(...)
    dot(a, b, out=None)

    Dot product of two arrays. Specifically,

    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).

    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.

    - If either `a` or `b` is 0-D (scalar), it is equivalent to
      :func:`multiply` and using ``numpy.multiply(a, b)`` or ``a * b`` is
      preferred.

    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.

    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of
      `b`::

        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])

    It uses an optimized BLAS library when possible (see `numpy.linalg`).

    Parameters
    ----------
    a : array_like
        Fir

Explore Numpy functions `linalg.norm` to obtain the magnitude/norm of the vectors `v1` and `v2`

In [60]:
np.linalg.norm(v1), np.linalg.norm(v2)

(np.float64(5.477225575051661), np.float64(7.3484692283495345))

Consider the cosine similarity function we build from scrach last week:

$$
  cos(v1, v2) = \frac{v1 . v2}{\lVert v1 \rVert \times \lVert v2 \rVert}
$$

Explore Numpy functions `linalg.norm` e `dot` and **re-write the cosine function** below without using a `for` loop.

In [61]:
def cosine_similarity(v1, v2):
    return np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2))

cosine_similarity(v1, v2)

np.float64(0.9441175904999112)

## Rectangular data

A lot of the datasets we study in Data Science are rectangular, like a spreadsheet or database table. This means that we have a  `n` and `m` columns.

* A **column** in the table is commonly referred to as a **variable**.
    * You may also see them refered as: attribute, input, predictor or feature
* A **row** in the table is commonly referred to as a **record**.
    * You may also see them refered as: case, example, instance, observation, pattern or sample


<details>
<p>

> Rectangular data is essentially a two-dimensional matrix with rows indicating records and columns indicating variables
> -- <cite>[Peter Bruce, Andrew Bruce @ Practical Statistics for Data Scientists][3]</cite>

[3]: https://www.oreilly.com/library/view/practical-statistics-for/9781491952955/ch01.html

</p>
</details>

What are independent and dependent variables?  

<details>
<p>
    
- An **independent variable** is the variable that is changed or controlled in a scientific experiment to test the effects on the dependent variable.  
    
- A **dependent variable** is the variable being tested and measured in a scientific experiment.
    
</p>
</details>

Very often what we want to do in data science is to explain how the independent variables can control the dependent variable.

What other names are given to these variables?

<details>
<p>

> an **independent variable** is sometimes called a "predictor variable", regressor, covariate, "manipulated variable", "explanatory variable", exposure variable (see reliability theory), "risk factor" (see medical statistics), "feature" (in machine learning and pattern recognition) or "input variable".
> -- <cite>[Wikipedia][4]</cite>
    
> a **dependent variable** is sometimes called a "response variable", "regressand", "criterion", "predicted variable", "measured variable", "explained variable", "experimental variable", "responding variable", "outcome variable", "output variable", "target" or "label".
> -- <cite>[Wikipedia][4]</cite>

[4]: https://en.wikipedia.org/wiki/Dependent_and_independent_variables#Statistics_synonyms


    
</p>
</details>

## Pandas

In [62]:
import pandas as pd

What is Pandas?

<details>
<p>

> Pandas is seriously a game changer when it comes to cleaning, transforming, manipulating and analyzing data. In simple terms, Pandas helps to clean the mess
> -- <cite>[Admond Lee][1]</cite>

[1]: https://towardsdatascience.com/why-and-how-to-use-pandas-with-large-data-9594dda2ea4c

</p>
</details>

Have a look at the Pandas documentation

<details>
<p>

> `pandas` is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool,
built on top of the Python programming language.
> -- <cite>[pandas library][2]</cite>

[2]: https://pandas.pydata.org/

</p>

- API reference: https://pandas.pydata.org/docs/reference/index.html#api

### Lets use Pandas to create a retangular dataset

The DataFrame object is a 2-dimensional labeled data structure with columns of potentially different types. You can think of it like a spreadsheet or SQL table. It is generally the most commonly used pandas object.

#### Constructing DataFrame

A Pandas DataFrame can be constructed in a variety of ways.

One of them is from a list of dicts:

Let's create a DataFrame from a list of dictionaries. Each dictionary represents a record and the keys represent the variables.

Desired DataFrame:

```python
        a	b
0	0	0
1	1	1
2	2	4
```



In [63]:
# create dataframe from a list of dictionaries to obtain the following output
#    a  b
# 0  0  0
# 1  1  1
# 2  2  4

# what should the items in the list be to obtain the output above?
data = [{'a': 0, 'b': 0}, {'a': 1, 'b': 1}, {'a': 2, 'b': 4}]

# use pd.DataFrame to create a dataframe from the "data"
pd.DataFrame(data)

a  b
0  0  0
1  1  1
2  2  4

In [64]:
# alternative way to create the dataframe from dictionary - this way requires the same list length for all keys (if a has 3 items, b must have 3 items)
data = {'a': [0, 1, 2], 'b': [0, 1, 4]}

pd.DataFrame(data)


a  b
0  0  0
1  1  1
2  2  4

Pandas creates tabular data structures called DataFrames and missing values are represented as `NaN` (**Not a Number**)
- if you don't provide values for a column, pandas will fill it with `NaN`
- Handling missing values is a big part of data cleaning and preparation process and defining strategies to deal with them are really important.

In [65]:
df = pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

In [66]:
df

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

A DataFrame object has an `index` and a `column` attribute
- `index` indicates the start, end (exclusive) and increment of the row indices

In [67]:
df.index

RangeIndex(start=0, stop=2, step=1)

- `columns` indicates the **column names** of the DataFrame and can be used to access columns

In [68]:
df.columns

Index(['a', 'b', 'c'], dtype='object')

**Casting to other data types** may help when working with those columns, try casting `df.columns` to a list

In [69]:
list(df.columns)

['a', 'b', 'c']

We can **rename** columns using the `rename` method

- Note that the columns were defined by the dictionary keys
- `inplace=True` will modify the DataFrame **in place**, otherwise a new DataFrame will be returned and the original will remain unchanged


In [70]:
# before:
df = pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])
df

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [71]:
# after - use rename to rename the columns 'a' to 'data' and 'b' to 'science'
df.rename(columns={'a': 'data', 'b': 'science'},inplace=True)

#### Creating your own DataFrame

Before learning more details and operations on DataFrames, lets create our own.

In [72]:
#       name	shoe	height
#   0	ana	    38  	168
#   1	bruno   39	    170
#   2	carlos	42	    174

name_list = ['ana', 'bruno', 'carlos']
shoe_list = [38, 39, 42]
height_list = [168, 170, 174]
gender_list = ['female', 'male','male']

# we are going to create a dataframe from the lists above - what should be the "keys" and "values" of the dictionary?
students_df = pd.DataFrame({'name': name_list, 'shoe': shoe_list, 'height': height_list})
students_df



name  shoe  height
0     ana    38     168
1   bruno    39     170
2  carlos    42     174

Print the `columns` of the DataFrame

In [73]:
students_df.columns

Index(['name', 'shoe', 'height'], dtype='object')

Print the `index` of the DataFrame

In [74]:
students_df.index

RangeIndex(start=0, stop=3, step=1)

We forgot the **gender data**. This is how we can add a new column to the DataFrame after it has been created
- Add a gender column with values `female`, `male`, `male`

In [75]:
students_df['gender'] = gender_list
students_df

name  shoe  height  gender
0     ana    38     168  female
1   bruno    39     170    male
2  carlos    42     174    male

We may have also introduced a wrong value. We can **access** it or **change** it using `loc`

In [76]:
students_df.iloc[2]

name      carlos
shoe          42
height       174
gender      male
Name: 2, dtype: object

Let's change the value of the `height` of the **carlos** record to `176`

In [77]:
students_df.loc[2, 'height'] = 176
students_df

name  shoe  height  gender
0     ana    38     168  female
1   bruno    39     170    male
2  carlos    42     176    male

We can also use the `iloc` method to access data by **position**
- use `iloc` to access the last row of the DataFrame

In [78]:
students_df.iloc[:2, [1, 2]]

# alternatively using negative index to access the last row of the dataframe

#students_df.iloc[-1]

shoe  height
0    38     168
1    39     170

- Use `iloc` to access the last element of the last column of the DataFrame
    
    - **Tip**: the DataFrame is matrix-like, so you can use the same indexing as you would use in a matrix (even negative indices work)

In [79]:
students_df.iloc[2, 2]

np.int64(176)

## Write and Read a csv file

We can use Pandas to perform both operations.
Run the cell below and check on your folder if the file was created.

In [80]:
# write a DataFrame as a csv file
students_df.to_csv('students.csv')

# if you don't want to save the index as a column in the csv file, use index=False
#students_df.to_csv('students_no_index.csv', index=False)

Read a csv file into a DataFrame - by **default**, `read_csv` assumes that the **delimiter is a comma**

In [81]:
# read the csv file into students_df2
students_df2 = pd.read_csv('students.csv')

# note that if you saved the csv file without index=False, the first column will be the index and will have no column name therefore pandas will assign it a default name 'Unnamed: 0'

In [82]:
# if the delimiter is differefrom default comma, you can specify it by using the keyword parameter "delimiter=" with the appropriate delimiter
# for example, if the delimiter is semicolon, you can use

#students_df2 = pd.read_csv('students.csv', delimiter=';')

Let's check if `students_df` is equal to `students_df2` using `.equals` method

In [83]:
students_df.equals(students_df2)

False

In [84]:
students_df

name  shoe  height  gender
0     ana    38     168  female
1   bruno    39     170    male
2  carlos    42     176    male

In [85]:
# notice that the index is saved as a column in the csv file
# if we want to avoid this, we can use the "index=False" argument when saving or reading the csv file
# students_df.to_csv('students.csv', index=False) for example
# we can also drop the index column after reading the csv file
# example of dropping the Unnamed column: students_df2.drop('Unnamed: 0', axis=1, inplace=True)
students_df2

Unnamed: 0    name  shoe  height  gender
0           0     ana    38     168  female
1           1   bruno    39     170    male
2           2  carlos    42     176    male

In [86]:
students_df2.drop('Unnamed: 0', axis=1, inplace=True)

# alternatively you can also use
#students_df2.drop(columns=['Unnamed: 0'], inplace=True) # you can add more column names in the list if you want to drop more than one column

When saving a DataFrame to a csv file, we can set the `index` to (`True` | `False`)

## Operations on pandas DataFrames

In this section you will learn about some DataFrame methods like `head` and `tail`.

### Subset of rows (records)

#### Select the first n rows

In [87]:
# first 2 rows
students_df.head(2)

name  shoe  height  gender
0    ana    38     168  female
1  bruno    39     170    male

In [88]:
students_df

name  shoe  height  gender
0     ana    38     168  female
1   bruno    39     170    male
2  carlos    42     176    male

In [89]:
(students_df['shoe']>=39) & (students_df['height']==170)


0    False
1     True
2    False
dtype: bool

In [90]:
students_df[students_df['name'].str.startswith('a')]

name  shoe  height  gender
0  ana    38     168  female

#### Select the last rows

In [91]:
# last 2 rows
students_df.tail(2)

name  shoe  height gender
1   bruno    39     170   male
2  carlos    42     176   male

#### Get a random sample of n rows

In [92]:
# everytime we use sample, we get a different output
# to get the same output, we can use the "random_state" argument like students_df.sample(2, random_state=42)
students_df.sample(2)

name  shoe  height  gender
1  bruno    39     170    male
0    ana    38     168  female

#### Select rows by position
- select the **first and second rows**

In [93]:
students_df.iloc[0: 2]

name  shoe  height  gender
0    ana    38     168  female
1  bruno    39     170    male

#### Select rows that meet logical criteria
- select all students with `height` of **170cm or higher**

In [94]:
students_df.loc[students_df['height'] >= 170]

name  shoe  height gender
1   bruno    39     170   male
2  carlos    42     176   male

#### Select rows based on multiple conditions
- select all `male` students with `height` of **172cm or higher**

In [95]:
# we need to use parantheses to separate the conditions when using "&" (and) like: (statement1) & (statement2)
# the same goes for "|" (or)

students_df.loc[(students_df['height'] >=172) & (students_df['gender'] == 'male')]

# alternatively, to make more readable

filter_height = students_df['height'] >= 170
filter_gender = students_df['gender'] == 'male'
students_df[filter_height & filter_gender] # or students_df.loc[filter_height &  filter_gender]

name  shoe  height gender
1   bruno    39     170   male
2  carlos    42     176   male

- select all `female` students with `height` of **172cm or higher**

In [96]:
# notice that there are no rows that satisfy the conditions
students_df.loc[(students_df['height'] >=172) & (students_df['gender'].str.contains('female')) ]

Empty DataFrame
Columns: [name, shoe, height, gender]
Index: []

### Subset of columns (variables)

#### Select columns by name

In [97]:
students_df.name

0       ana
1     bruno
2    carlos
Name: name, dtype: object

Select subset of columns `name` and `gender`

In [98]:
students_df[['name', 'gender']]

name  gender
0     ana  female
1   bruno    male
2  carlos    male

#### Select columns by position
Using `iloc[rows, columns]` to select
- select the **first and third columns** of the dataframe

In [99]:
# returns all rows and columns 1 and 3
students_df.iloc[:, [1, 3]]

shoe  gender
0    38  female
1    39    male
2    42    male

### Subset of both rows and columns
- select the rows where the `shoe` size is **greater than 40** and **only** the columns `name` and `shoe`

In [100]:
students_df.loc[(students_df.shoe > 40), ['name', 'shoe']]

name  shoe
2  carlos    42

### Summing Up

* When selecting subsets of data, square brackets `[]` are used.
* Inside these brackets, you can use a single column/row label, a list of column/row labels, a slice of labels, a conditional expression or a colon.
* Select specific rows and/or columns using **loc** when using the row and column names.
* Select specific rows and/or columns using **iloc** when using the positions in the table.
* You can assign new values to a selection based on **loc/iloc**.

[This](https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf) Pandas Cheat Sheet might come in handy.

## Challenges

In these challenges you will handle a bigger dataset.

There are a few first questions you need to know how to answer before reading a CSV file with Pandas

- Does the CSV have a header line?
- Is there an index column?
- What is the separator character on the CSV file?
- If there are missing values, is there any specific word being used to describe a missing value?

Then, these details can be handled by specifing some parameters as `sep`, `na_values` or `index_col`.

### Challenge 1 - Load the dataset

In [101]:
# load titanic dataset
df_titanic = pd.read_csv('titanic.csv')

### Challenge 2 - Validate the loading

1. Show the first 10 rows and confirm if the table matches with the lines


In [102]:
df_titanic.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

2. Try the DataFrame method `info`. It is a nice alternative.

In [103]:
df_titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


What information do you get from this?

In [104]:
# the "info" method shows the number of non-null values in each column, data types and size in memory

### Challenge 3 - Some basic EDA

**EDA** stands for `Exploratory Data Analysis`. It is used by data scientists to analyze and investigate data sets and summarize their main characteristics, often employing data visualization methods.

Try executing `df_titanic.describe()`.

In [105]:
df_titanic.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

After investigating the results, describe them and comment on the usefulness of this Pandas function.

In [106]:
# describe method presents a summary of the data with the count, mean, std, min, 25%, 50%, 75%, and max values
# 25%, 50%, and 75% are the 1st, 2nd, and 3rd quartiles
# quartiles are values that divide the data into four equal parts

### Challenge 4 - Getting to know your data

What do the results above tell you about each variable? Do you actually now what they mean?

This is a crutial step. For info on this dataset click [here](https://www.kaggle.com/competitions/titanic/data?select=train.csv).



In [107]:
# Your comments here

---

## Additional Challenge

This challenge is solved to help you get familiar with the most important object of the NumPy library, the array.

### Part I

1. Use the numpy's function `arange` and create the array `my_array` with the sequence of numbers from 0 to 24.

In [108]:
my_array = np.arange(24)
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

2. Use the method `reshape` to redimension the array so that it has 6 rows and 4 columns. What happened? What is the relasionship between the number of elements and the dimensions of a 2D matrix?

In [109]:
my_array = my_array.reshape((6,4))
my_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

###  Part II

$$\begin{bmatrix}
1 & 2 & 1 & 7 \\
3 & 0 & 1 & 8 \\
0 & 2 & 4 & 9 \\
2 & 2 & 5 & 5
\end{bmatrix}$$

1. Create this matrix in NumPy

In [110]:
m = np.array([[1, 2, 1, 7],
            [3, 0, 1, 8],
            [0, 2, 4, 9],
            [2, 2, 5, 5]])

print(m, '\n')

# Pergunta 3.2: primeira coluna,
# não há necessidade de saber as dimensões da matriz
print('first column: \n', m[:,0], '\n')

# Pergunta 3.3: slice primeira coluna mas so as filas 2 e 3
# não há necessidade de saber as dimensões da matriz
print('first column, rows 2 and 3: \n', m[1:3,0], '\n')

# Pergunta 3.4: slice os quatro elementos no centro da matriz
# este slice usa o conhecimento do tamanho da matriz
# no caso geral será necessário escrever uma função que determine
# o slice
print('centre: \n', m[1:3,1:3], '\n')

# Pergunta 3.5: slice a sub-matriz dos quatro elementos no canto inferior
# direito, sem usar o tamanho da matriz.
# esta versão não cumpre o requerimento, porque conta desde o início da matriz
# e portanto está a usar informação do tamanho da mesma para atingir o
# objetivo
print('bottom right: \n', m[2:,2:], '\n')


# Pergunta 3.5: slice a sub-matriz dos quatro elementos no canto inferior
# direito, sem usar o tamanho da matriz.
# esta versão sim cumpre o requerimento, porque define o slice desde o fim
# da matriz
print('bottom right: \n', m[-2:,-2:], '\n')

# Pergunta 3.6: slice a sub-matriz dos quatro elementos no canto inferior
# direito, sem usar o tamanho da matriz.

# esta versão usa informação do tamanho da matriz para definir a seleção
# de colunas
print('top right: \n', m[:2,2:], '\n')

# esta versão cumpre o requerimento
print('top right: \n', m[:-2,-2:], '\n')

# esta versão cumpre o requerimento
print('top right: \n', m[:2,-2:], '\n')

[[1 2 1 7]
 [3 0 1 8]
 [0 2 4 9]
 [2 2 5 5]] 

first column: 
 [1 3 0 2] 

first column, rows 2 and 3: 
 [3 0] 

centre: 
 [[0 1]
 [2 4]] 

bottom right: 
 [[4 9]
 [5 5]] 

bottom right: 
 [[4 9]
 [5 5]] 

top right: 
 [[1 7]
 [1 8]] 

top right: 
 [[1 7]
 [1 8]] 

top right: 
 [[1 7]
 [1 8]] 



**Expected output**:

```python

first column:
 [1 3 0 2]

first column, rows 2 and 3:
 [3 0]

centre:
 [[0 1]
 [2 4]]

bottom right:
 [[4 9]
 [5 5]]

bottom right:
 [[4 9]
 [5 5]]

top right:
 [[1 7]
 [1 8]]

top right:
 [[1 7]
 [1 8]]

top right:
 [[1 7]
 [1 8]]
```